language: r # implies pandoc and LaTeX

before_install:
  - sudo apt-get install jq pdf2svg
  - tlmgr install totpages ncctools cmap cm-super standalone

install:
  - npm install
  - git clone https://github.com/jakobib/hypertext2019.git html

script:
  - make
  - make -C short-version
